apiVersion: v1
kind: Service
metadata:
  name: rent-price-api-service
spec:
  selector: 
    app: rent-price-api
  ports:
  - protocol: "TCP"
    port: 5444
    targetPort: 81
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rent-price-api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rent-price-api
  template:
    metadata:
      labels:
        app: rent-price-api
    spec:
      containers:
      - image: rent-price-api1:latest
        imagePullPolicy: Never
        name: rent-price-api
        ports:
        - containerPort: 81
      restartPolicy: Always
