apiVersion: v1
kind: Service
metadata:
  name: house-price-api-service
spec:
  selector: 
    app: house-price-api
  ports:
  - protocol: "TCP"
    port: 5443
    targetPort: 82
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: house-price-api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: house-price-api
  template:
    metadata:
      labels:
        app: house-price-api
    spec:
      containers:
      - image: house_price_api:latest
        imagePullPolicy: Never
        name: house-price-api
        ports:
        - containerPort: 82
      restartPolicy: Always
